[project]
name = "db-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "litestar[standard]>=2.17.0",
    "sqlalchemy>=2.0.43",
    "sqlalchemy-utils>=0.42.0",
]

[dependency-groups]
dev = [
    "ruff>=0.13.0",
]

[tool.ruff.format]
quote-style = "single"
